--[[---------------------------------------------------------------------------
Door groups
---------------------------------------------------------------------------
The server owner can set certain doors as owned by a group of people, identified by their jobs.


HOW TO MAKE A DOOR GROUP:
AddDoorGroup("NAME OF THE GROUP HERE, you will see this when looking at a door", Team1, Team2, team3, team4, etc.)
---------------------------------------------------------------------------]]
-- Example: AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
-- Example: AddDoorGroup("Gundealer only", TEAM_GUN)
AddDoorGroup("Альянс", TEAM_OTAFANTOM, TEAM_MPF12, TEAM_OBS, TEAM_ELITE4, TEAM_MAYOR, TEAM_BARNEY, TEAM_MPF1, TEAM_MPF2, TEAM_MPF3, TEAM_MPF4, TEAM_MPF5, TEAM_MPF6, TEAM_MPF7, TEAM_MPF8, TEAM_MPF9, TEAM_MPF10, TEAM_MPF11, TEAM_CMD1, TEAM_CMD2, TEAM_CMD3, TEAM_CMD4, TEAM_OTA1, TEAM_OTA2, TEAM_OTA3, TEAM_OTA4, TEAM_OTA5, TEAM_OTA6, TEAM_OTANOVA1, TEAM_OTANOVA2, TEAM_OTANOVA2, TEAM_OTANOVA3, TEAM_CREMATOR, TEAM_STALKER)
AddDoorGroup("Командование", TEAM_MAYOR, TEAM_CMD1, TEAM_CMD2, TEAM_CMD3, TEAM_OTA5, TEAM_CMD4, TEAM_MPF10, TEAM_STALKER)
AddDoorGroup("Кабинет главы ГСР", TEAM_GSR6, TEAM_OBS, TEAM_MAYOR, TEAM_CMD1, TEAM_CMD2, TEAM_CMD3, TEAM_OTA5, TEAM_CMD4, TEAM_MPF11)
AddDoorGroup("Музыкальный бар", TEAM_GSR3, TEAM_OBS, TEAM_GSR6, TEAM_MAYOR, TEAM_BARNEY, TEAM_MPF1, TEAM_MPF2, TEAM_MPF3, TEAM_MPF4, TEAM_MPF5, TEAM_MPF6, TEAM_MPF7, TEAM_MPF8, TEAM_MPF9, TEAM_MPF10, TEAM_MPF11, TEAM_CMD1, TEAM_CMD2, TEAM_CMD3, TEAM_CMD4, TEAM_OTA1, TEAM_OTA2, TEAM_OTA3, TEAM_OTA4, TEAM_OTA5, TEAM_OTA6, TEAM_OTANOVA1, TEAM_OTANOVA2, TEAM_OTANOVA2, TEAM_OTANOVA3)
AddDoorGroup("ГСР", TEAM_GSR1, TEAM_GSR2, TEAM_OBS, TEAM_GSR3, TEAM_GSR4, TEAM_GSR5, TEAM_GSR6, TEAM_MAYOR, TEAM_BARNEY, TEAM_MPF1, TEAM_MPF2, TEAM_MPF3, TEAM_MPF4, TEAM_MPF5, TEAM_MPF6, TEAM_MPF7, TEAM_MPF8, TEAM_MPF9, TEAM_MPF10, TEAM_MPF11, TEAM_CMD1, TEAM_CMD2, TEAM_CMD3, TEAM_CMD4, TEAM_OTA1, TEAM_OTA2, TEAM_OTA3, TEAM_OTA4, TEAM_OTA5, TEAM_OTA6, TEAM_OTANOVA1, TEAM_OTANOVA2, TEAM_OTANOVA2, TEAM_OTANOVA3)
AddDoorGroup("Больница ГСР", TEAM_GSR4, TEAM_OBS, TEAM_GSR6, TEAM_MAYOR, TEAM_BARNEY, TEAM_MPF1, TEAM_MPF2, TEAM_MPF3, TEAM_MPF4, TEAM_MPF5, TEAM_MPF6, TEAM_MPF7, TEAM_MPF8, TEAM_MPF9, TEAM_MPF10, TEAM_MPF11, TEAM_CMD1, TEAM_CMD2, TEAM_CMD3, TEAM_CMD4, TEAM_OTA1, TEAM_OTA2, TEAM_OTA3, TEAM_OTA4, TEAM_OTA5, TEAM_OTA6, TEAM_OTANOVA1, TEAM_OTANOVA2, TEAM_OTANOVA2, TEAM_OTANOVA3)
AddDoorGroup("Завод ГСР", TEAM_GSR5, TEAM_GSR2, TEAM_OBS, TEAM_GSR6, TEAM_MAYOR, TEAM_BARNEY, TEAM_MPF1, TEAM_MPF2, TEAM_MPF3, TEAM_MPF4, TEAM_MPF5, TEAM_MPF6, TEAM_MPF7, TEAM_MPF8, TEAM_MPF9, TEAM_MPF10, TEAM_MPF11, TEAM_CMD1, TEAM_CMD2, TEAM_CMD3, TEAM_CMD4, TEAM_OTA1, TEAM_OTA2, TEAM_OTA3, TEAM_OTA4, TEAM_OTA5, TEAM_OTA6, TEAM_OTANOVA1, TEAM_OTANOVA2, TEAM_OTANOVA2, TEAM_OTANOVA3)
AddDoorGroup("Сопротивление", TEAM_FOODSHOP, TEAM_GANG2, TEAM_AGENT, TEAM_GANG8, TEAM_GANG3, TEAM_GANG4, TEAM_GANG5, TEAM_GANG6, TEAM_GANG7, TEAM_GUNSHOP, TEAM_GMED, TEAM_GFAST, TEAM_ARMY, TEAM_GSPY, TEAM_BANG1, TEAM_KLEINER, TEAM_BARNEY, TEAM_ALYX, TEAM_GORDON, TEAM_ELITE1, TEAM_ELITE2, TEAM_ELITE3, TEAM_ELITE4, TEAM_ELITE5, TEAM_GPYRO)
